name: block-position-cycle-presentation
app: dockerfile

resources:
  spot: true
  cpu: 0
  memory: 1
  disk: 0
  replicas: 1

options:
  ports: 8501
  dockerfile: Dockerfile

context:
  git:
    url: git@github.com:shortpeng96/block-position-cycle-deploy.git
    branch: main
  preset: dockerfile
