name: block-position-cycle-presentation
app: dockerfile

options:
  ports: 8501
  dockerfile: Dockerfile

context:
  git:
    url: git@github.com:shortpeng96/block-position-cycle-deploy.git
    branch: main
  preset: dockerfile
