name: block-position-cycle-presentation
app: dockerfile

options:
  ports: 8501
  dockerfile: Dockerfile

context:
  git:
    url: https://github.com/BigYard-labs/block-position-cycle-project.git
    branch: main
  preset: dockerfile
